language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
# command to install dependencies
install:
  - "pip install pycrypto"
  - "pip install 'paramiko<1.15'"
  - "pip install coveralls"
# command to run tests
script: cd tests/Exscript/; coverage run ./run_suite.py 1
after_success:
  coveralls
